services:
  docs-tigrbl-com:
    build: .
    container_name: docs-tigrbl-com
    restart: unless-stopped
    labels:
      site.host: docs.tigrbl.com
      site.kind: zdx-docs
    expose:
      - "80"
    networks:
      dockerwp:
        aliases:
          - docs-tigrbl-com

networks:
  dockerwp:
    name: dockerwp
    external: true
